sudo: required
dist: trusty
language: php

services:
  - mysql

php:
  - 7.0

cache:
  directories:
    - vendor

before_script:
    - cp .env.travis .env
    - mysql -e 'create database homestead_test;'
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate
    - php artisan serve > /dev/null 2>&1 &
    - php artisan migrate
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &


script:
    - php artisan dusk
    - php artisan dusk:email-screenshots