sudo: required
dist: trusty
language: php

php:
  - 5.6

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - cp .env.travis .env

    - mysql -e 'create database vipadmin;'
    - composer self-update
    - composer install --no-interaction
    - php artisan serve > /dev/null 2>&1 &

script:
    - php artisan dusk